### ISSUE TITLE
Structuring suggestions

### ISSUE THREAD

**Issue by mmhamdy** [NousResearch/Open-Reasoning-Tasks#5]
Hi,

This is an amazing initiative!  The idea of compiling a comprehensive list of potential reasoning tasks for language model evaluation is really valuable. I have a couple of suggestions:

1. This is about all possible reasoning tasks, and not just tasks associated with datasets or a published paper? If so, I think it would be helpful to mention that in the contributing section.

2. If the task has an associated dataset or a paper, it would be nice to include those in the schema for reference.

3. Organizing the tasks in one big markdown file would make it harder to check if a task has already been added. Creating a tasks folder with each task in its own markdown file would make it much easier to check and navigate.

4. Following the previous structure, maybe we can render those markdown files into a github page for ease of access and search.

I can work on the folder structure, website rendering, and updating the contributing section. I just need your approval before starting to work on it.

**Comment by N8python** [comment]
Agreed. There is a lot of structure issues - the markdown file is more of a temporary idea haha. 1 is true yes - any reasoning task we can think of. 2 is good. 

The one thing I'm concerned about (3) is that we could end up with a folder with like 1000s of files haha.

(4) sounds really good.

**Comment by N8python** [comment]
I agree. That could work. Or we could group related tasks together in the same file.

**Comment by teknium1** [comment]
> Hi,
> 
> This is an amazing initiative! The idea of compiling a comprehensive list of potential reasoning tasks for language model evaluation is really valuable. I have a couple of suggestions:
> 
> 1. This is about all possible reasoning tasks, and not just tasks associated with datasets or a published paper? If so, I think it would be helpful to mention that in the contributing section.
> 2. If the task has an associated dataset or a paper, it would be nice to include those in the schema for reference.
> 3. Organizing the tasks in one big markdown file would make it harder to check if a task has already been added. Creating a tasks folder with each task in its own markdown file would make it much easier to check and navigate.
> 4. Following the previous structure, maybe we can render those markdown files into a github page for ease of access and search.
> 
> I can work on the folder structure, website rendering, and updating the contributing section. I just need your approval before starting to work on it.

This is for all possible reasoning tasks, with a bias toward LLM but not necessarily LLM (text) only reasoning. 

I think I do agree that having a master list with task name and description, and a link to the full doc for that task is probably a better schema, it will also make merging PR's easier since people wont have a lot of conflicts to deal with as it grows

A web rendered version of the repo is a great idea. Currently I think our schema is not looking aesthetically pleasing or readable in it's current state, and would be happy to accept a new way to layout the markdown for each task to make it so.

Also it was discussed that we should probably add some new required fields to the schema, including modalities required (i.e. Image input, Text Output, etc), a topoly of upper order classes of reasoning to fit each task into, and open ended tags for potentially easier searching of the documents later.

**Comment by teknium1** [comment]
Also I think yet another field for any citation or reference to where the idea for the task came from, a doc/structured repo for "Reasoning Formats" (i.e. prolog use, some kind of unique language, etc) for use as its own list/set of docs, and a master list of reasoning in AI papers as well seems like a good direction too. Many people have come to the project hoping to contribute reasoning formats and prompting structures, systems, etc - there should be a place for that here too

**Comment by teknium1** [comment]
Also if you dont mind, hop on our discord to discuss this a bit more in depth live :)

https://discord.gg/nousresearch

**Comment by mmhamdy** [comment]
Cool! Will continue the discussion on discord.

**Comment by N8python** [comment]
As far as I can see it got restructured :D.
